ckanext-weca-tdh/ckanext/weca_tdh/lib/forms.py
import json
import os

_forms_cache = None


def load_forms():
    global _forms_cache
    if _forms_cache is None:
        path = os.path.join(os.path.dirname(__file__), "..", "config", "forms.json")
        with open(path, "r") as f:
            _forms_cache = json.load(f)
    return _forms_cache


def get_form(form_name):
    forms = load_forms()
    return next((f for f in forms if f["name"] == form_name), None)

ckanext-weca-tdh/ckanext/weca_tdh/controller.py
import json

import ckan.plugins.toolkit as toolkit
from flask import Blueprint, request

import ckanext.weca_tdh.config as C
from ckanext.weca_tdh.lib.helpers import update_package_metadata_list

actionbp = Blueprint('action', __name__)


class Controller(object):
    @staticmethod
    def update_dataset_interest(dataset_id):
        pkg_dict = toolkit.get_action('package_show')({}, {'id': dataset_id})
        user_email = toolkit.g.userobj.email

        update_package_metadata_list(pkg_dict, key='expressed_interest', value=user_email)

        return toolkit.redirect_to('dataset.read', id=dataset_id)
    
    @staticmethod
    def download_tdh_partner_connect_file() -> str:
        tdh_catalog = request.args.get('tdh_catalog', '')  # or set a default
        tdh_schema = request.args.get('tdh_schema', '')

        # get config values
        host = C.TDH_CONNECT_ADDRESS_HOST
        path = C.TDH_CONNECT_ADDRESS_PATH

        # create partner connect file
        file = {
            "version": "0.1",
            "connections": [
                {
                    "details": {
                        "protocol": "databricks-sql",
                        "address": {
                            "host": host, 
                            "path": path
                        },
                        "authentication": None,
                        "query": None,
                    },
                    "options": {
                        "Catalog": tdh_catalog, 
                        "Database": tdh_schema
                    },
                    "mode": "DirectQuery",
                }
            ],
        }

        return json.dumps(file)

actionbp.add_url_rule('/dataset/<dataset_id>/interest', 'dataset_interest',
                          view_func=Controller.update_dataset_interest)
actionbp.add_url_rule('/tdh_partner_connect_file', 'tdh_partner_connect_file', 
                          view_func=Controller.download_tdh_partner_connect_file)

ckanext-weca-tdh/ckanext/weca_tdh/platform/databricks/auth.py
import time

import ckan.plugins.toolkit as toolkit
from flask import flash, request, session

from .utils import oauth_code_verify_and_challenge
from .workspace import DatabricksWorkspace


def authenticate(resource_id):
    action = request.args.get("autodownload")
    referrer = request.args.get("referrer", "/dataset")
    code_verifier, code_challenge = oauth_code_verify_and_challenge()

    session['databricks'] = {
        "action": action,
        "code_verifier": code_verifier,
        "referrer": referrer,
        "resource_id": resource_id
    }

    auth_url = DatabricksWorkspace.build_databricks_auth_url(code_challenge, resource_id)
    return toolkit.redirect_to(auth_url)


def authorise():
    workspace = DatabricksWorkspace()
    try:
        action = session.get('databricks', {}).get('action')
        referrer = session.get('databricks', {}).get('referrer', '/')
        resource_id = session.get('databricks', {}).get('resource_id')

        auth_code = workspace.get_workspace_auth_code()
        code_verifier = session.get('databricks', {}).get('code_verifier')

        response_dict = workspace.generate_workspace_access_token(code_verifier, auth_code)

        access_token = response_dict.get("access_token")
        refresh_token = response_dict.get("refresh_token")

        now = time.time()
        expires_at = int(now) + int(response_dict.get("expires_in", 3600))
        refresh_expires_at = int(now) + 604800 # 7 days

        workspace.set_tokens(access_token, refresh_token, expires_at, refresh_expires_at)
        session.pop('databricks', None)
        
        if resource_id:
            sep = "&" if "?" in referrer else "?"
            referrer = f"{referrer}{sep}autodownload={action}"

        return toolkit.redirect_to(referrer)

    except Exception as e:
        flash(f"Download authorisation failed: {e}.", category='alert-danger')
        return toolkit.redirect_to(referrer)

ckanext-weca-tdh/ckanext/weca_tdh/platform/databricks/views.py
from flask import Blueprint

from .auth import authenticate, authorise
from .download import (
    download_file, 
    get_download_task_status, 
    start_download
)
from .query import (
    download_query_file, 
    get_query_task_status, 
    start_query_download
)

databricksbp = Blueprint('databricks', __name__)

databricksbp.add_url_rule('/databricks/auth/initiate/<resource_id>', 
                          view_func=authenticate)
databricksbp.add_url_rule('/databricks/auth', 
                          view_func=authorise)

databricksbp.add_url_rule('/databricks/download/start', 
                          view_func=start_download, methods=['POST'])
databricksbp.add_url_rule('/databricks/download/status', 
                          view_func=get_download_task_status, methods=['POST'])
databricksbp.add_url_rule('/databricks/download/<task_id>', 
                          view_func=download_file, methods=['GET'])

databricksbp.add_url_rule('/databricks/query/start_download', 
                          view_func=start_query_download, methods=['POST'])
databricksbp.add_url_rule('/databricks/query/status', 
                          view_func=get_query_task_status, methods=['POST'])
databricksbp.add_url_rule('/databricks/query/download/<task_id>', 
                          view_func=download_query_file, methods=['GET'])

ckanext-weca-tdh/ckanext/weca_tdh/platform/upload/views.py
import logging

from ckanext.weca_tdh.platform.upload.logic import handle_upload_get, handle_upload_post
from flask import Blueprint
from flask.views import MethodView

log = logging.getLogger(__name__)
uploadbp = Blueprint("upload", __name__)


class BlobUploadView(MethodView):

    def get(self, id, resource_id):
        return handle_upload_get(id, resource_id)

    def post(self, id, resource_id):
        return handle_upload_post(id, resource_id)


uploadbp.add_url_rule(
    "/dataset/<id>/upload_form/<resource_id>",
    view_func=BlobUploadView.as_view(str("blob")),
)

ckanext-weca-tdh/ckanext/weca_tdh/templates/ckanext_pages/base_Form.html
{% ckan_extends %}

{% block form_basic_fields %}
  {{ form.input('title', id='field-title', label=_('Title'), placeholder=title_placeholder, value=data.title, error=errors.title, classes=['control-full', 'control-large'], attrs={'data-module': 'slug-preview-target', 'class': 'form-control'}) }}

  {% set domain = slug_domain|replace("http://", "")|replace("https://", "") %}
  {% set attrs = {'data-module': 'slug-preview-slug', 'data-module-prefix': domain~'/', 'data-module-placeholder': '<page>', 'class': 'form-control input-sm'} %}
  {{ form.prepend('name', id='field-name', label=_('URL'), prepend=slug_prefix, placeholder=_(url_placeholder), value=data.name, error=errors.name, attrs=attrs, is_required=true) }}

  <div class="form-group control-medium">
    <label for="field-publish_date" class="form-label">{{ _('Publish Date') }}</label>
    <div class="controls">
      {% set value = h.render_datetime(data.publish_date, date_format='%Y-%m-%d') %}
      <input value="{{value}}" type="date" id="field-publish_date" name="publish_date" class="form-control">
    </div>
  </div>
{% endblock %}

{% block extra_pages_form %}
  {% set options = [{'value': False, 'text': _('No')}, {'value': True, 'text': _('Yes')}]%}
  {{ form.select('pin_page', id='pin_page', label='Pin to top', options=options, selected=data.pin_page) }}

  <small id="summary-char-count" class="char-count text-muted">{{ _('250 characters remaining') }}</small>
  {% set attrs = {'maxlength': 250, 'class': 'form-control', 'oninput': 'updateCharCount(this)'} %}
  {{ form.textarea('summary', id='field-summary', label=_('Summary'), value=data.summary, placeholder='Short Summary', error=errors.summary, attrs=attrs) }}

  <script>
    function updateCharCount(textarea) {
      var max = textarea.maxLength;
      var current = textarea.value.length;
      var remaining = max - current;
      var counter = document.getElementById('summary-char-count');
      if (counter) {
        counter.textContent = remaining + " characters remaining";
      }
    }

    document.addEventListener('DOMContentLoaded', function () {
      var textarea = document.getElementById('field-summary');
      if (textarea) {
        updateCharCount(textarea);
      }
    });
  </script>
{% endblock extra_pages_form %}

ckanext-weca-tdh/ckanext/weca_tdh/templates/ckanext_pages/base_form.html
{% ckan_extends %}

{% block form_basic_fields %}
  {{ form.input('title', id='field-title', label=_('Title'), placeholder=title_placeholder, value=data.title, error=errors.title, classes=['control-full', 'control-large'],
   attrs={'data-module': 'slug-preview-target', 'class': 'form-control'}) }}

  {% set domain = slug_domain|replace("http://", "")|replace("https://", "") %}
  {% set attrs = {'data-module': 'slug-preview-slug', 'data-module-prefix': domain~'/', 'data-module-placeholder': '<page>', 'class': 'form-control input-sm'} %}
  {{ form.prepend('name', id='field-name', label=_('URL'), prepend=slug_prefix, placeholder=_(url_placeholder), value=data.name, error=errors.name, attrs=attrs, is_required=true) }}

  <div class="form-group control-medium">
    <label for="field-publish_date" class="form-label">{{ _('Publish Date') }}</label>
    <div class="controls">
      {% set value = h.render_datetime(data.publish_date, date_format='%Y-%m-%d') %}
      <input value="{{value}}" type="date" id="field-publish_date" name="publish_date" class="form-control">
    </div>
  </div>
{% endblock %}

{% block extra_pages_form %}
  {% set options = [{'value': False, 'text': _('No')}, {'value': True, 'text': _('Yes')}]%}
  {{ form.select('pin_page', id='pin_page', label='Pin to top', options=options, selected=data.pin_page) }}

  <small id="summary-char-count" class="char-count text-muted">{{ _('250 characters remaining') }}</small>
  {% set attrs = {'maxlength': 250, 'class': 'form-control', 'oninput': 'updateCharCount(this)'} %}
  {{ form.textarea('summary', id='field-summary', label=_('Summary'), value=data.summary, placeholder='Short Summary', error=errors.summary, attrs=attrs) }}

  <script>
    function updateCharCount(textarea) {
      var max = textarea.maxLength;
      var current = textarea.value.length;
      var remaining = max - current;
      var counter = document.getElementById('summary-char-count');
      if (counter) {
        counter.textContent = remaining + " characters remaining";
      }
    }

    document.addEventListener('DOMContentLoaded', function () {
      var textarea = document.getElementById('field-summary');
      if (textarea) {
        updateCharCount(textarea);
      }
    });
  </script>
{% endblock extra_pages_form %}

{% block form_visibility_fields %}
  <div class="control-group form-group">
    <label for="field-visibility" class="control-label">{{ _('Visibility') }}</label>
    <div class="controls">
      <select id="field-visibility" class="form-control" name="visibility">
        {% for option in [("public", _('Public')), ("restricted", _('Restricted')), ("private", _('Private'))] %}
        <option value="{{ option[0] }}" {% if option[0] == data.visibility %}selected="selected"{% endif %}>{{ option[1] }}</option>
        {% endfor %}
      </select>
    </div>
  </div>

  <input type="hidden" id="field-private" name="private"
        value="{{ 'true' if data.visibility == 'private' else 'false' }}">

  <script>
    document.addEventListener('DOMContentLoaded', function () {
      var visibilitySelect = document.getElementById('field-visibility');
      var privateInput = document.getElementById('field-private');

      function updatePrivateFlag() {
        var visibility = visibilitySelect.value;
        privateInput.value = visibility === 'private' ? 'true' : 'false';
      }

      visibilitySelect.addEventListener('change', updatePrivateFlag);
      updatePrivateFlag();
    });
  </script>
{% endblock %}

ckanext-weca-tdh/ckanext/weca_tdh/templates/ckanext_pages/blog.html
{% ckan_extends %}

{% block subtitle %}{{ c.page.title }}{% endblock %}

{% block breadcrumb_content %}
  <li class="active">{% link_for _('Articles'), named_route='pages.blog_index' %}</li>
  <li class="active">{% link_for c.page.title, named_route='pages.blog_show', page=c.page.name %}</li>
{% endblock %}

{% block primary_content %}
  <section class="module govuk-body">
    {% block ckanext_pages_actions %}
      {% if h.check_access('ckanext_pages_update') %}
        {% asset 'pages/main-css' %}
        {% link_for _('Edit'), named_route='pages.blog_edit', page=c.page.name, class_='btn btn-primary pull-right page-action', icon='plus-square' %}
        {% link_for _('Revisions'), named_route='pages.blog_revisions', page=c.page.name, class_='btn btn-primary pull-right page-action me-2', icon='eye' %}
      {% endif %}
    {% endblock %}

    <h1>{{ c.page.title }}</h1>

    {% if c.page.publish_date %}
      <span class="muted date"> {{ h.render_datetime(c.page.publish_date) }} </span>
    {% endif %}

    {% block ckanext_pages_content %}
      {% if c.page.content %}
        <div class="ckanext-pages-content">
          {% set editor = h.pages_get_wysiwyg_editor() %}
          {% if editor %}
            <div>
              {{ c.page.content|safe }}
            </div>
          {% else %}
            {{ h.render_markdown_gfm(c.page.content) | safe }}
          {% endif %}
        </div>
      {% else %}
        <p class="empty">{{ _('This article currently has no content.') }}</p>
      {% endif %}
    {% endblock %}
  </section>
{% endblock %}

{% block secondary_content %}
  {% set posts = h.get_recent_blog_posts(number=5, exclude=c.page.name) %}

  <div class="module module-narrow module-shallow">
    <h2 class="module-heading">
      {{ _('Latest Articles') }}
    </h2>
    <div class="module-content">
      {% for post in posts %}
        <div class="blog-title">
          <h3 class="dataset-heading">
            <a class="govuk-link" href="{{ h.url_for('pages.blog_show', page=post.name) }}">{{ post.title or post.name }}</a>
            <br>
            {% if post.publish_date %}
              <small>{{ h.render_datetime(post.publish_date) }}</small>
            {% endif %}
          </h3>
        </div>
        <div class="blog-content">
          {{ h.markdown_extract(post.summary) }}
          {% if post.publish_date %}
            <br>
            <a class="btn btn-small btn-primary more" href="{{ h.url_for('pages.blog_show', page=post.name) }}">{{ _('More') }}</a>
          {% endif %}
        </div>
      {% endfor %}
    </div>
  </div>

{% asset 'pages/blog-css' %}
{% endblock %}

ckanext-weca-tdh/ckanext/weca_tdh/templates/ckanext_pages/blog_edit.html
{% extends 'ckanext_pages/blog_edit_base.html' %}

{% block subtitle %}{{ _('Edit Article')}} {% endblock %}

{% block breadcrumb_content %}
  <li class="active">{% link_for _('Articles'), named_route='pages.blog_index' %}</li>
  {% if data.title %}
    <li class="active">{% link_for data.title, named_route='pages.blog_show', page=page %}</li>
    <li class="active">{% link_for _('Edit'), named_route='pages.blog_edit', page=page %}</li>
  {% else %}
    <li class="active">{% link_for _('Add'), named_route='pages.blog_new', page=page %}</li>
  {% endif %}
{% endblock %}

{% block primary_content_inner %}
  {% snippet 'ckanext_pages/base_form.html', page=page, data=data, errors=errors, hide_field_order=true, type='blog' %}
{% endblock %}

{% block primary %}
  <section class="module govuk-body">
    {{ self.primary_content_inner() }}
  </section>
{% endblock %}

{% block secondary %}{% endblock %}

ckanext-weca-tdh/ckanext/weca_tdh/templates/ckanext_pages/blog_list.html
{% extends 'ckanext_pages/blog_edit_base.html' %}

{% block breadcrumb_content %}
  <li class="active">{% link_for _('Articles'), named_route='pages.blog_index' %}</li>
{% endblock %}

{% block primary %}
  <article class="module govuk-body" role="main">
    {% if h.check_access('ckanext_pages_update', {}) %}
      {% link_for _('Add Article'), named_route='pages.blog_new', page='', class_='btn btn-primary page-action', icon='plus-square' %}
    {% endif %}
    {% snippet 'ckanext_pages/snippets/pages_list.html', pages=c.page.items, type='blog', title='Articles' %}
    {{ c.page.pager() }}
  </article>
{% endblock %}

{% block secondary %}{% endblock %}

ckanext-weca-tdh/ckanext/weca_tdh/templates/ckanext_pages/blog_revisions.html
{% ckan_extends %}

{% block breadcrumb_content %}
  <li class="active">{% link_for _('Articles'), named_route='pages.blog_index' %}</li>
  <li class="active">{% link_for c.page.title, named_route='pages.blog_show', page=c.page.name %}</li>
  <li class="active">{% link_for _('Revisions'), named_route='pages.blog_revisions', page=c.page.name %}</li>
{% endblock %}

{% block primary %}
  <section class="module govuk-body">
    {% block ckanext_pages_actions %}
      {% if h.check_access('ckanext_pages_update') %}
        {% asset 'pages/main-css' %}
        {% link_for _('View Page'), named_route='pages.blog_show', page=c.page.name, class_='btn btn-primary pull-right page-action', icon='eye' %}
      {% endif %}
    {% endblock %}

    <h1 class="page-heading">{{ c.page.title }}</h1>

    {% if c.page.revisions %}
      <div class="ckanext-pages-content">
        <ul class="activity">
          {% for key, revision in c.page.get_ordered_revisions().items() %}
            <li class="item">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x icon"></i>
                <i class="fa fa-users fa-stack-1x fa-inverse"></i>
              </span>
              {{ _('{actor} updated page at {date}').format(
                actor=actor(revision), date=h.render_datetime(revision.created, with_hours=True)
              )|safe }}
              {% link_for _('Preview'), named_route='pages.blog_revisions_preview', page=c.page.name, revision=key, class_='btn btn-default' %}
              {% if not revision.current %}
                {% link_for _('Restore'), named_route='pages.blog_revision_restore', page=c.page.name, revision=key, class_='btn btn-primary' %}
              {% else %}
                <span class="badge badge-inverse">{{ _('Active Revision') }}</span>
              {% endif %}
              <br/>
              <span class="date" title="{{ h.render_datetime(revision.created, with_hours=True) }}">
                {{ h.time_ago_from_timestamp(revision.created) }}
              </span>
            </li>
            {% endfor %}
        </ul>
      </div>
    {% else %}
      <p class="empty">{{ _('This article currently has no revisions') }}</p>
    {% endif %}
  </section>
{% endblock %}

ckanext-weca-tdh/ckanext/weca_tdh/templates/ckanext_pages/edit_base.html
{% ckan_extends %}

{% block subtitle %}{{ _('Support') }}{% endblock %}

ckanext-weca-tdh/ckanext/weca_tdh/templates/ckanext_pages/page.html
{% extends 'page.html' %}

{% block subtitle %}{{ c.page.title }}{% endblock %}

{% block breadcrumb_content %}
  <li class="active">{% link_for _('Support'), named_route='pages.pages_index' %}</li>
  <li class="active">{% link_for c.page.title, named_route='pages.show', page=c.page.name %}</li>
{% endblock %}

{% block primary %}
  <section class="module govuk-body">
    {% block ckanext_pages_actions %}
      {% if h.check_access('ckanext_pages_update') %}
        {% asset 'pages/main-css' %}
        {% link_for _('Edit'), named_route='pages.edit', page=c.page.name, class_='btn btn-primary pull-right page-action', icon='edit' %}
        {% link_for _('Revisions'), named_route='pages.pages_revisions', page=c.page.name, class_='btn btn-primary pull-right page-action me-2', icon='eye' %}
      {% endif %}
    {% endblock %}

    <h1>{{ c.page.title }}</h1>

    {% block ckanext_pages_content %}
      {% if c.page.content %}
        <div class="ckanext-pages-content">
          {% set editor = h.pages_get_wysiwyg_editor() %}
          {% if editor %}
            <div>
              {{ c.page.content|safe }}
            </div>
          {% else %}
            {{ h.render_markdown_gfm(c.page.content) | safe }}
          {% endif %}
        </div>
      {% else %}
        <p class="empty">{{ _('This page currently has no content.') }}</p>
      {% endif %}
    {% endblock %}
  </section>
{% endblock %}

ckanext-weca-tdh/ckanext/weca_tdh/templates/ckanext_pages/snippets/featured_blogs.html
{% set blogs_total = blogs|length %}

{% if blogs %}
  {% for blog in blogs %}
    {% set url = h.url_for('pages.blog_show', page=blog.name) %}
    {% snippet 'ckanext_pages/snippets/page_item.html', url=url, page=blog, featured=True %}
  {% endfor %}
{% else %}
  <p class="empty">
    {{ _('There are currently no articles.') }}
  </p>
{% endif %}

ckanext-weca-tdh/ckanext/weca_tdh/templates/package/macros/data_access.html
{% macro render(res, tdh_schema) %}
  {% set data_access_info = {
    'File Download': {
      'title': "Direct Download",
      'icon': 'fa-solid fa-download',
      'description': 'This resource is available to download directly from the TDH.'
    },
    'Power BI Report': {
      'title': 'Power BI Report',
      'img': "/assets/images/branding/pbi-logo.svg",
      'description': 'A Power BI Report is available for this resource. To view the report, click the Go to resource button above.'
    },
    'TDH Query': {
      'title': "Connect with Power BI",
      'img': "/assets/images/branding/pbi-logo.svg",
      'description': "This resource is available to query using Power BI. <a href='/pages/tdh_partner_connect' aria-label='Data access'>
        <i class='fa fa-info-circle info-icon' title='Learn how to connect to the Transport Data Hub.' aria-hidden='true'></i></a>"
    },
    'External Link': {
      'title': 'Signposted Data',
      'icon': 'fa-solid fa-arrow-up-right-from-square',
      'description': 'This resource is available through an external link. To view, click the Go to resource button above.'
    },
    'Preview': {
      'title': 'Preview',
      'icon': 'fa-solid fa-chart-simple',
      'description': 'This resource is available to preview using the sample data below.'
    }
  } %}

  {% set access = data_access_info.get(res.resource_data_access) %}
  {% if not access %}
    <p>{{ _('A data access type has not been assigned to this resource.') }}</p>
  {% else %}
    <div class="data-access-summary">
      {% if res.resource_data_access == "File Download" %}
        <a id="ga-file-download-db" class="btn btn-primary resource-data-action"
          {% if h.user_has_valid_db_token() %}
            onclick="return start_download('{{ res.id }}');"
          {% else %}
            href="{{ h.url_for('databricks.authenticate', resource_id=res.id) }}?referrer={{ request.path }}&autodownload={{ res.id }}"
          {% endif %}>
          <i class="fa fa-arrow-circle-down"></i> {{ _('Download File') }}
          <div id="download-spinner" class="download-spinner"></div>
        </a>
      {% elif res.resource_data_access == "TDH Query" %}
        <a id="ga-tdh-connect" 
           class="btn btn-primary resource-data-action" 
           href="{{ h.url_for('action.tdh_partner_connect_file') }}?tdh_catalog={{ res.tdh_catalog }}&tdh_schema={{ tdh_schema }}" 
           download="TDH-{{ res.name | replace(' ', '_') }}.pbids">
            <i class="fa fa-arrow-circle-down"></i> {{ _('Partner Connect File') }}
        </a>
      {% endif %}

      <h2>
        {{ access.title }}
        {% if access.img %}
          <span class="data-access-img" aria-hidden="true">
            <img src="{{ access.img }}" alt="{{ access.title }}" width="30" height="30"/>
          </span>
        {% elif access.icon %}
          <span class="data-access-icon" aria-hidden="true">
            <i class="{{ access.icon }}"></i>
          </span>
        {% endif %}
      </h2>

      <p>{{ access.description | safe }}</p>

      {% if res.resource_data_access == "TDH Query" %}
        {% if res.tdh_catalog and tdh_schema and res.tdh_table %}
          <div class="tdh-query-block">
            <label for="tdh-query-path">{{ _('TDH Query Path') }}</label>
            <div class="tdh-query-path">
              <code id="tdh-query-path">{{ res.tdh_catalog }}.{{ tdh_schema }}.{{ res.tdh_table }}</code>
              <button onclick="copyQueryPath()" aria-label="Copy query path">
                <i id="tdh-query-path-icon" class="fa-regular fa-copy" aria-hidden="true"></i>
              </button>
            </div>
          </div>

          {% set queries = h.load_json(res.resource_queries) %}
          {% if queries %}
            <p class="content-seperator" style="margin-top: 1rem;"></p>
            <div class="tdh-query-block">
              <h2>{{ _('Data download') }}
                <span class="data-access-icon" aria-hidden="true">
                  <i class="fa fa-arrow-circle-down"></i>
                </span>
              </h2>
              <p>{{ _('Download data directly using the queries below:') }}</p>
            </div>
            <div class="tdh-query-block">
              {% for query in queries %}
                {% set loop_index = loop.index0 %}
                {% set query_id = "tdh-query-" ~ loop_index %}
                {% set query_spinner_id = "query-spinner-" ~ loop_index %}

                <div class="{% if not loop.first %}tdh-query-block{% endif %}">
                  <div class="accordion" id="queryAccordion">
                    <div id="{{query_id}}" class="accordion-item">
                      <h2 class="accordion-header" id="heading-{{loop_index}}">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{{loop_index}}">
                          {{ query.title or 'Query ' ~ loop_index }}
                        </button>
                      </h2>
                      <div id="collapse-{{loop_index}}" class="accordion-collapse collapse" data-bs-parent="#queryAccordion">
                        <div class="accordion-body">
                          <a role="button" id="ga-res-query-db-{{query_id}}" class="btn btn-primary dropdown-toggle resource-data-action" 
                            data-bs-toggle="dropdown" aria-expanded="false" aria-label="list of downloadable formats">         
                            <span class="caret">
                              <i class="fa fa-arrow-circle-down" style="margin-right:5px;"></i>
                              {{ _('Download') }}
                            </span>
                            <div id="{{query_spinner_id}}" class="download-spinner"></div>
                          </a>
                          <ul class="dropdown-menu" aria-labelledby="ga-res-query-db-{{ query_id }}">
                            <li class="dropdown-header">
                              <i class="fa fa-arrow-circle-down"></i> {{ _('Choose format') }}
                            </li>
                            {% for format in query.formats %}
                              <li style="cursor:pointer;">
                                <a class="dropdown-item"
                                  {% if h.user_has_valid_db_token() %}
                                    onclick="return start_query_download('{{ res.id }}', '{{ loop_index }}', '{{ format | lower }}');"
                                  {% else %}
                                    {% set args = loop_index ~ '_' ~ format | lower %}
                                    href="{{ h.url_for('databricks.authenticate', resource_id=res.id) }}?referrer={{ request.path }}&autodownload={{ args }}"
                                  {% endif %}>
                                  {{ format | upper }}    
                                </a>
                              </li>
                            {% else %}
                              <li class="dropdown-item disabled text-muted">{{ _('No formats available') }}</li>
                            {% endfor %}
                          </ul>
                          <p>{{ query.summary }}</p>
                          <small>{{ "Available format(s): " ~ query.formats | join(', ') | upper }}</small>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
            <p class="content-seperator" style="margin-top: 1rem;"></p>
          {% endif %}
        {% endif %}
      {% endif %}
    </div>
  {% endif %}
{% endmacro %}